[project]
name = "passenger-screening-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "trail3r", email = "gusdnr7223@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[project.scripts]
passenger-screening-research = "passenger_screening_research:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
